SET NAMES utf8mb4;

INSERT INTO mydatabase.`Type` (name_type) VALUES
	 ('Fleurs'),
	 ('Fruits'),
	 ('Légumes'),
	 ('Plantes');

INSERT INTO mydatabase.Family (name_family,name_type) VALUES
	 ('Cucurbitacées','Légumes'),
	 ('Liliacées','Légumes'),
	 ('Chénopodiacées','Légumes'),
	 ('Astéracées','Légumes'),
	 ('Solanacées','Légumes'),
	 ('Brassicacées','Légumes'),
	 ('Apiacées','Légumes'),
	 ('Fabacées','Légumes'),
	 ('Valérianacées','Légumes'),
	 ('Amarantacées','Légumes'),
	 ('Poacées','Légumes'),
	 ('Convolvulacées','Légumes'),
	 ('Polygonacées','Légumes');

INSERT INTO mydatabase.Species (name_species,radius,name_icon,plantation_start,plantation_end,harvest_duration,name_family) VALUES
	 ('Citrouille',50.0,NULL,4,10,6,'Cucurbitacées'),
	 ('Concombre',20.0,NULL,4,10,6,'Cucurbitacées'),
	 ('Cornichon',20.0,NULL,4,10,6,'Cucurbitacées'),
	 ('Courge',20.0,NULL,4,10,6,'Cucurbitacées'),
	 ('Courgette',20.0,NULL,4,10,6,'Cucurbitacées'),
	 ('Melon',20.0,NULL,4,10,6,'Cucurbitacées'),
	 ('Pasteque',20.0,NULL,4,10,6,'Cucurbitacées'),
	 ('Potimarron',20.0,NULL,4,10,6,'Cucurbitacées'),
	 ('Potiron',30.0,NULL,4,10,6,'Cucurbitacées'),
	 ('Courge butternut',50.0,NULL,5,10,4,'Cucurbitacées'),
	 ('Courge spaghetti',50.0,NULL,5,10,4,'Cucurbitacées'),
	 ('Patidou',50.0,NULL,5,10,4,'Cucurbitacées'),
	 ('Pâtisson',50.0,NULL,5,9,8,'Cucurbitacées'),
	 ('Ail',20.0,NULL,2,7,3,'Liliacées'),
	 ('Asperge',40.0,NULL,4,6,8,'Liliacées'),
	 ('Échalote',20.0,NULL,2,7,3,'Liliacées'),
	 ('Oignon',6.0,NULL,3,8,4,'Liliacées'),
	 ('Poireau',8.0,NULL,3,11,8,'Liliacées'),
	 ('Arroche',20.0,NULL,4,9,12,'Chénopodiacées'),
	 ('Betterave',12.0,NULL,4,9,8,'Chénopodiacées'),
	 ('Blette',20.0,NULL,4,10,16,'Chénopodiacées'),
	 ('Artichaut',50.0,NULL,6,9,12,'Astéracées'),
	 ('Endive',15.0,NULL,5,11,6,'Astéracées'),
	 ('Salade',20.0,NULL,3,10,8,'Astéracées'),
	 ('Aubergine',30.0,NULL,6,10,10,'Solanacées'),
	 ('Piment',25.0,NULL,6,10,10,'Solanacées'),
	 ('Poivron',25.0,NULL,6,10,10,'Solanacées'),
	 ('Pomme de terre',20.0,NULL,5,9,4,'Solanacées'),
	 ('Tomate',30.0,NULL,6,10,12,'Solanacées'),
	 ('Brocoli',30.0,NULL,6,10,4,'Brassicacées'),
	 ('Chou de bruxelles',23.0,NULL,9,12,8,'Brassicacées'),
	 ('Chou chinois',23.0,NULL,7,9,4,'Brassicacées'),
	 ('Chou kale',23.0,NULL,8,12,12,'Brassicacées'),
	 ('Chou pommé',23.0,NULL,6,11,6,'Brassicacées'),
	 ('Chou romanesco',23.0,NULL,8,11,4,'Brassicacées'),
	 ('Chou-fleur',23.0,NULL,6,11,4,'Brassicacées'),
	 ('Chou-rave',23.0,NULL,5,9,4,'Brassicacées'),
	 ('Navet',20.0,NULL,3,10,6,'Brassicacées'),
	 ('Radis',4.0,NULL,3,9,3,'Brassicacées'),
	 ('Radis noir',8.0,NULL,7,10,4,'Brassicacées'),
	 ('Roquette',10.0,NULL,4,9,5,'Brassicacées'),
	 ('Carotte',10.0,NULL,3,10,12,'Apiacées'),
	 ('Céleri',20.0,NULL,5,10,8,'Apiacées'),
	 ('Fenouil',20.0,NULL,5,10,6,'Apiacées'),
	 ('Panais',20.0,NULL,4,11,8,'Apiacées'),
	 ('Edamame',8.0,NULL,5,9,4,'Fabacées'),
	 ('Fève',15.0,NULL,3,7,4,'Fabacées'),
	 ('Haricots à rame',15.0,NULL,5,9,10,'Fabacées'),
	 ('Haricots nains',20.0,NULL,5,9,8,'Fabacées'),
	 ('Petit pois',10.0,NULL,3,7,4,'Fabacées'),
	 ('Pois gourmand',10.0,NULL,3,7,4,'Fabacées'),
	 ('Mâche',10.0,NULL,8,11,8,'Valérianacées'),
	 ('Épinard',20.0,NULL,3,10,6,'Amarantacées'),
	 ('Maïs',20.0,NULL,5,9,4,'Poacées'),
	 ('Patate douce',30.0,NULL,5,10,4,'Convolvulacées'),
	 ('Rhubarbe',70.0,NULL,4,7,12,'Polygonacées');

INSERT INTO mydatabase.Variety (name_variety,radius,name_icon,plantation_start,plantation_end,harvest_duration,name_species) VALUES
	 ('Black beauty',20.0,NULL,4,10,6,'Courgette'),
	 ('Blanche d''égypte',20.0,NULL,4,10,6,'Courgette'),
	 ('Gold Rush',20.0,NULL,4,10,6,'Courgette'),
	 ('Ronde de nice',20.0,NULL,4,10,6,'Courgette'),
	 ('Citrouille grosse orange de Paris',NULL,NULL,NULL,NULL,NULL,'Citrouille'),
	 ('Citrouille Jack O''Lantern',NULL,NULL,NULL,NULL,NULL,'Citrouille'),
	 ('Concombre Marketmore',NULL,NULL,NULL,NULL,NULL,'Concombre'),
	 ('Concombre vert long maraîcher',NULL,NULL,NULL,NULL,NULL,'Concombre'),
	 ('Cornichon vert petit de Paris',NULL,NULL,NULL,NULL,NULL,'Cornichon'),
	 ('Cornichon vert fin de Meaux',NULL,NULL,NULL,NULL,NULL,'Cornichon'),
	 ('Melon Charentais',NULL,NULL,NULL,NULL,NULL,'Melon'),
	 ('Melon Cantaloup',NULL,NULL,NULL,NULL,NULL,'Melon'),
	 ('Pastèque Sugar Baby',NULL,NULL,NULL,NULL,NULL,'Pasteque'),
	 ('Pastèque Crimson Sweet',NULL,NULL,NULL,NULL,NULL,'Pasteque'),
	 ('Potimarron Uchiki Kuri',NULL,NULL,NULL,NULL,NULL,'Potimarron'),
	 ('Potimarron Blue Kuri',NULL,NULL,NULL,NULL,NULL,'Potimarron'),
	 ('Potiron jaune gros de Paris',NULL,NULL,NULL,NULL,NULL,'Potiron'),
	 ('Potiron galeux d''Eysines',NULL,NULL,NULL,NULL,NULL,'Potiron'),
	 ('Butternut Waltham',NULL,NULL,NULL,NULL,NULL,'Courge butternut'),
	 ('Butternut musquée de Provence',NULL,NULL,NULL,NULL,NULL,'Courge butternut'),
	 ('Spaghetti Vegetable',NULL,NULL,NULL,NULL,NULL,'Courge spaghetti'),
	 ('Tivoli',NULL,NULL,NULL,NULL,NULL,'Courge spaghetti'),
	 ('Sweet Dumpling',NULL,NULL,NULL,NULL,NULL,'Patidou'),
	 ('Table King',NULL,NULL,NULL,NULL,NULL,'Patidou'),
	 ('Pâtisson blanc',NULL,NULL,NULL,NULL,NULL,'Pâtisson'),
	 ('Pâtisson jaune',NULL,NULL,NULL,NULL,NULL,'Pâtisson'),
	 ('Ail rose de Lautrec',NULL,NULL,NULL,NULL,NULL,'Ail'),
	 ('Ail violet de Cadours',NULL,NULL,NULL,NULL,NULL,'Ail'),
	 ('Argenteuil',NULL,NULL,NULL,NULL,NULL,'Asperge'),
	 ('Grolim',NULL,NULL,NULL,NULL,NULL,'Asperge'),
	 ('Échalote grise',NULL,NULL,NULL,NULL,NULL,'Échalote'),
	 ('Échalote de Jersey',NULL,NULL,NULL,NULL,NULL,'Échalote'),
	 ('Oignon jaune paille des Vertus',NULL,NULL,NULL,NULL,NULL,'Oignon'),
	 ('Oignon rouge de Florence',NULL,NULL,NULL,NULL,NULL,'Oignon'),
	 ('Poireau bleu de Solaise',NULL,NULL,NULL,NULL,NULL,'Poireau'),
	 ('Poireau gros long d''été',NULL,NULL,NULL,NULL,NULL,'Poireau'),
	 ('Arroche rouge',NULL,NULL,NULL,NULL,NULL,'Arroche'),
	 ('Arroche blonde',NULL,NULL,NULL,NULL,NULL,'Arroche'),
	 ('Betterave crapaudine',NULL,NULL,NULL,NULL,NULL,'Betterave'),
	 ('Betterave chioggia',NULL,NULL,NULL,NULL,NULL,'Betterave'),
	 ('Blette verte à carde blanche',NULL,NULL,NULL,NULL,NULL,'Blette'),
	 ('Blette de Lucullus',NULL,NULL,NULL,NULL,NULL,'Blette'),
	 ('Camus de Bretagne',NULL,NULL,NULL,NULL,NULL,'Artichaut'),
	 ('Violet de Provence',NULL,NULL,NULL,NULL,NULL,'Artichaut'),
	 ('Witloof',NULL,NULL,NULL,NULL,NULL,'Endive'),
	 ('Endive de Bruxelles',NULL,NULL,NULL,NULL,NULL,'Endive'),
	 ('Batavia blonde',NULL,NULL,NULL,NULL,NULL,'Salade'),
	 ('Laitue à couper',NULL,NULL,NULL,NULL,NULL,'Salade'),
	 ('Aubergine violette de Barbentane',NULL,NULL,NULL,NULL,NULL,'Aubergine'),
	 ('Aubergine ronde de Valence',NULL,NULL,NULL,NULL,NULL,'Aubergine'),
	 ('Piment d''Espelette',NULL,NULL,NULL,NULL,NULL,'Piment'),
	 ('Piment de Cayenne',NULL,NULL,NULL,NULL,NULL,'Piment'),
	 ('Poivron Yolo Wonder',NULL,NULL,NULL,NULL,NULL,'Poivron'),
	 ('Poivron Corno di Toro',NULL,NULL,NULL,NULL,NULL,'Poivron'),
	 ('Bintje',NULL,NULL,NULL,NULL,NULL,'Pomme de terre'),
	 ('Charlotte',NULL,NULL,NULL,NULL,NULL,'Pomme de terre'),
	 ('Cœur de bœuf',NULL,NULL,NULL,NULL,NULL,'Tomate'),
	 ('Roma',NULL,NULL,NULL,NULL,NULL,'Tomate'),
	 ('Calabrese',NULL,NULL,NULL,NULL,NULL,'Brocoli'),
	 ('De Cicco',NULL,NULL,NULL,NULL,NULL,'Brocoli'),
	 ('Groninger',NULL,NULL,NULL,NULL,NULL,'Chou de bruxelles'),
	 ('Rubine',NULL,NULL,NULL,NULL,NULL,'Chou de bruxelles'),
	 ('Granaat',NULL,NULL,NULL,NULL,NULL,'Chou chinois'),
	 ('Wong Bok',NULL,NULL,NULL,NULL,NULL,'Chou chinois'),
	 ('Kale Nero di Toscana',NULL,NULL,NULL,NULL,NULL,'Chou kale'),
	 ('Kale Red Russian',NULL,NULL,NULL,NULL,NULL,'Chou kale'),
	 ('Chou de Bonneuil',NULL,NULL,NULL,NULL,NULL,'Chou pommé'),
	 ('Chou cabus',NULL,NULL,NULL,NULL,NULL,'Chou pommé'),
	 ('Romanesco Natalino',NULL,NULL,NULL,NULL,NULL,'Chou romanesco'),
	 ('Romanesco Veronica',NULL,NULL,NULL,NULL,NULL,'Chou romanesco'),
	 ('Chou-fleur de Lyon',NULL,NULL,NULL,NULL,NULL,'Chou-fleur'),
	 ('Chou-fleur Merveille de Caen',NULL,NULL,NULL,NULL,NULL,'Chou-fleur'),
	 ('Vienne blanc',NULL,NULL,NULL,NULL,NULL,'Chou-rave'),
	 ('Vienne violet',NULL,NULL,NULL,NULL,NULL,'Chou-rave'),
	 ('Navet de Croissy',NULL,NULL,NULL,NULL,NULL,'Navet'),
	 ('Navet boule d''or',NULL,NULL,NULL,NULL,NULL,'Navet'),
	 ('Radis de 18 jours',NULL,NULL,NULL,NULL,NULL,'Radis'),
	 ('Radis rond rose à bout blanc',NULL,NULL,NULL,NULL,NULL,'Radis'),
	 ('Radis noir gros long d''hiver',NULL,NULL,NULL,NULL,NULL,'Radis noir'),
	 ('Radis noir de Chine',NULL,NULL,NULL,NULL,NULL,'Radis noir'),
	 ('Roquette cultivée',NULL,NULL,NULL,NULL,NULL,'Roquette'),
	 ('Roquette sauvage',NULL,NULL,NULL,NULL,NULL,'Roquette'),
	 ('Carotte de Nantes',NULL,NULL,NULL,NULL,NULL,'Carotte'),
	 ('Carotte Touchon',NULL,NULL,NULL,NULL,NULL,'Carotte'),
	 ('Céleri-rave Monarch',NULL,NULL,NULL,NULL,NULL,'Céleri'),
	 ('Céleri branche doré',NULL,NULL,NULL,NULL,NULL,'Céleri'),
	 ('Fenouil de Florence',NULL,NULL,NULL,NULL,NULL,'Fenouil'),
	 ('Fenouil doux de Sicile',NULL,NULL,NULL,NULL,NULL,'Fenouil'),
	 ('Panais demi-long de Guernesey',NULL,NULL,NULL,NULL,NULL,'Panais'),
	 ('Panais blanc du Vaucluse',NULL,NULL,NULL,NULL,NULL,'Panais'),
	 ('Edamame Midori Giant',NULL,NULL,NULL,NULL,NULL,'Edamame'),
	 ('Edamame Chiba Green',NULL,NULL,NULL,NULL,NULL,'Edamame'),
	 ('Fève Aguadulce',NULL,NULL,NULL,NULL,NULL,'Fève'),
	 ('Fève de Séville à longue cosse',NULL,NULL,NULL,NULL,NULL,'Fève'),
	 ('Haricot à rame Blauhilde',NULL,NULL,NULL,NULL,NULL,'Haricots à rame'),
	 ('Haricot à rame Cobra',NULL,NULL,NULL,NULL,NULL,'Haricots à rame'),
	 ('Haricot nain Contender',NULL,NULL,NULL,NULL,NULL,'Haricots nains'),
	 ('Haricot nain vert de Chine',NULL,NULL,NULL,NULL,NULL,'Haricots nains'),
	 ('Merveille de Kelvedon',NULL,NULL,NULL,NULL,NULL,'Petit pois'),
	 ('Douce Provence',NULL,NULL,NULL,NULL,NULL,'Petit pois'),
	 ('Carouby de Maussane',NULL,NULL,NULL,NULL,NULL,'Pois gourmand'),
	 ('Sugar Snap',NULL,NULL,NULL,NULL,NULL,'Pois gourmand'),
	 ('Mâche à grosse graine',NULL,NULL,NULL,NULL,NULL,'Mâche'),
	 ('Mâche verte de Cambrai',NULL,NULL,NULL,NULL,NULL,'Mâche'),
	 ('Épinard géant d''hiver',NULL,NULL,NULL,NULL,NULL,'Épinard'),
	 ('Épinard monstrueux de Viroflay',NULL,NULL,NULL,NULL,NULL,'Épinard'),
	 ('Maïs doux Golden Bantam',NULL,NULL,NULL,NULL,NULL,'Maïs'),
	 ('Maïs doux Early Extra Sweet',NULL,NULL,NULL,NULL,NULL,'Maïs'),
	 ('Patate douce Beauregard',NULL,NULL,NULL,NULL,NULL,'Patate douce'),
	 ('Patate douce Bonita',NULL,NULL,NULL,NULL,NULL,'Patate douce'),
	 ('Rhubarbe Victoria',NULL,NULL,NULL,NULL,NULL,'Rhubarbe'),
	 ('Rhubarbe Cherry Red',NULL,NULL,NULL,NULL,NULL,'Rhubarbe');

INSERT INTO mydatabase.Association (name_species,name_species_1,isPositive) VALUES
	 ('Citrouille','Courgette',FALSE),
	 ('Pasteque','Potiron',FALSE),
	 ('Ail','Tomate',TRUE),
	 ('Ail','Carotte',TRUE),
	 ('Oignon','Carotte',TRUE),
	 ('Oignon','Betterave',TRUE),
	 ('Oignon','Chou pommé',TRUE),
	 ('Oignon','Salade',TRUE),
	 ('Oignon','Tomate',TRUE),
	 ('Oignon','Pomme de terre',TRUE),
	 ('Oignon','Épinard',TRUE),
	 ('Échalote','Carotte',TRUE),
	 ('Échalote','Betterave',TRUE),
	 ('Échalote','Blette',TRUE),
	 ('Échalote','Salade',TRUE),
	 ('Poireau','Carotte',TRUE),
	 ('Poireau','Céleri',TRUE),
	 ('Poireau','Tomate',TRUE),
	 ('Tomate','Carotte',TRUE),
	 ('Tomate','Asperge',TRUE),
	 ('Aubergine','Épinard',TRUE),
	 ('Poivron','Aubergine',TRUE),
	 ('Piment','Carotte',TRUE),
	 ('Pomme de terre','Haricots nains',TRUE),
	 ('Pomme de terre','Petit pois',TRUE),
	 ('Pomme de terre','Haricots à rame',TRUE),
	 ('Chou pommé','Céleri',TRUE),
	 ('Chou pommé','Salade',TRUE),
	 ('Chou pommé','Betterave',TRUE),
	 ('Chou pommé','Carotte',TRUE),
	 ('Chou pommé','Fève',TRUE),
	 ('Brocoli','Fève',TRUE),
	 ('Brocoli','Céleri',TRUE),
	 ('Brocoli','Pomme de terre',TRUE),
	 ('Chou de bruxelles','Fève',TRUE),
	 ('Chou de bruxelles','Céleri',TRUE),
	 ('Chou de bruxelles','Pomme de terre',TRUE),
	 ('Chou-fleur','Fève',TRUE),
	 ('Chou-fleur','Betterave',TRUE),
	 ('Chou-fleur','Céleri',TRUE),
	 ('Chou-fleur','Pomme de terre',TRUE),
	 ('Chou-rave','Chou kale',TRUE),
	 ('Chou-rave','Chou romanesco',TRUE),
	 ('Chou-rave','Chou chinois',TRUE),
	 ('Chou-rave','Maïs',TRUE),
	 ('Chou-rave','Salade',TRUE),
	 ('Chou kale','Betterave',TRUE),
	 ('Chou kale','Céleri',TRUE),
	 ('Chou kale','Oignon',TRUE),
	 ('Chou kale','Radis',TRUE),
	 ('Chou kale','Salade',TRUE),
	 ('Chou romanesco','Céleri',TRUE),
	 ('Navet','Petit pois',TRUE),
	 ('Navet','Oignon',TRUE),
	 ('Radis','Fève',TRUE),
	 ('Radis','Concombre',TRUE),
	 ('Radis','Salade',TRUE),
	 ('Radis','Carotte',TRUE),
	 ('Radis','Épinard',TRUE),
	 ('Radis','Tomate',TRUE),
	 ('Radis noir','Salade',TRUE),
	 ('Radis noir','Épinard',TRUE),
	 ('Radis noir','Carotte',TRUE),
	 ('Radis noir','Ail',TRUE),
	 ('Roquette','Salade',TRUE),
	 ('Roquette','Mâche',TRUE),
	 ('Roquette','Épinard',TRUE),
	 ('Carotte','Petit pois',TRUE),
	 ('Carotte','Pois gourmand',TRUE),
	 ('Céleri','Oignon',TRUE),
	 ('Céleri','Tomate',TRUE),
	 ('Céleri','Fève',TRUE),
	 ('Panais','Haricots nains',TRUE),
	 ('Panais','Maïs',TRUE),
	 ('Panais','Oignon',TRUE),
	 ('Panais','Pomme de terre',TRUE),
	 ('Panais','Radis',TRUE),
	 ('Concombre','Fève',TRUE),
	 ('Concombre','Brocoli',TRUE),
	 ('Concombre','Céleri',TRUE),
	 ('Concombre','Salade',TRUE),
	 ('Concombre','Petit pois',TRUE),
	 ('Cornichon','Maïs',TRUE),
	 ('Cornichon','Concombre',TRUE),
	 ('Courgette','Céleri',TRUE),
	 ('Courgette','Fève',TRUE),
	 ('Courgette','Haricots à rame',TRUE),
	 ('Courgette','Maïs',TRUE),
	 ('Courgette','Oignon',TRUE),
	 ('Courgette','Petit pois',TRUE),
	 ('Melon','Maïs',TRUE),
	 ('Citrouille','Fève',TRUE),
	 ('Citrouille','Maïs',TRUE),
	 ('Citrouille','Radis',TRUE),
	 ('Potiron','Maïs',TRUE),
	 ('Potiron','Haricots à rame',TRUE),
	 ('Potimarron','Maïs',TRUE),
	 ('Potimarron','Haricots à rame',TRUE),
	 ('Courge butternut','Maïs',TRUE),
	 ('Courge butternut','Haricots à rame',TRUE),
	 ('Courge butternut','Oignon',TRUE),
	 ('Courge butternut','Ail',TRUE),
	 ('Courge butternut','Petit pois',TRUE),
	 ('Courge spaghetti','Maïs',TRUE),
	 ('Courge spaghetti','Haricots à rame',TRUE),
	 ('Pâtisson','Carotte',TRUE),
	 ('Pâtisson','Fève',TRUE),
	 ('Pâtisson','Salade',TRUE),
	 ('Pâtisson','Maïs',TRUE),
	 ('Petit pois','Épinard',TRUE),
	 ('Petit pois','Maïs',TRUE),
	 ('Petit pois','Chou-fleur',TRUE),
	 ('Betterave','Céleri',TRUE),
	 ('Betterave','Salade',TRUE),
	 ('Betterave','Ail',TRUE),
	 ('Betterave','Radis',TRUE),
	 ('Épinard','Chou pommé',TRUE),
	 ('Épinard','Céleri',TRUE),
	 ('Épinard','Carotte',TRUE),
	 ('Épinard','Poireau',TRUE),
	 ('Blette','Chou pommé',TRUE),
	 ('Blette','Salade',TRUE),
	 ('Blette','Carotte',TRUE),
	 ('Arroche','Betterave',TRUE),
	 ('Arroche','Carotte',TRUE),
	 ('Endive','Carotte',TRUE),
	 ('Endive','Navet',TRUE),
	 ('Endive','Radis',TRUE),
	 ('Rhubarbe','Petit pois',TRUE),
	 ('Rhubarbe','Fève',TRUE),
	 ('Salade','Carotte',TRUE),
	 ('Mâche','Salade',TRUE),
	 ('Asperge','Artichaut',TRUE),
	 ('Asperge','Concombre',TRUE),
	 ('Asperge','Petit pois',TRUE),
	 ('Artichaut','Aubergine',TRUE),
	 ('Artichaut','Chou-fleur',TRUE),
	 ('Artichaut','Fève',TRUE),
	 ('Artichaut','Tomate',TRUE),
	 ('Ail','Fève',FALSE),
	 ('Ail','Haricots nains',FALSE),
	 ('Ail','Chou pommé',FALSE),
	 ('Ail','Pomme de terre',FALSE),
	 ('Ail','Artichaut',FALSE),
	 ('Oignon','Fève',FALSE),
	 ('Oignon','Haricots nains',FALSE),
	 ('Oignon','Concombre',FALSE),
	 ('Échalote','Fève',FALSE),
	 ('Échalote','Haricots nains',FALSE),
	 ('Échalote','Poireau',FALSE),
	 ('Échalote','Ail',FALSE),
	 ('Échalote','Chou pommé',FALSE),
	 ('Échalote','Pomme de terre',FALSE),
	 ('Poireau','Fève',FALSE),
	 ('Poireau','Haricots nains',FALSE),
	 ('Poireau','Betterave',FALSE),
	 ('Poireau','Chou pommé',FALSE),
	 ('Poireau','Brocoli',FALSE),
	 ('Tomate','Aubergine',FALSE),
	 ('Tomate','Poivron',FALSE),
	 ('Tomate','Piment',FALSE),
	 ('Tomate','Pomme de terre',FALSE),
	 ('Tomate','Fenouil',FALSE),
	 ('Tomate','Maïs',FALSE),
	 ('Tomate','Melon',FALSE),
	 ('Tomate','Pasteque',FALSE),
	 ('Tomate','Chou pommé',FALSE),
	 ('Tomate','Betterave',FALSE),
	 ('Tomate','Rhubarbe',FALSE),
	 ('Tomate','Concombre',FALSE),
	 ('Aubergine','Fenouil',FALSE),
	 ('Aubergine','Pomme de terre',FALSE),
	 ('Poivron','Fenouil',FALSE),
	 ('Piment','Fenouil',FALSE),
	 ('Pomme de terre','Rhubarbe',FALSE),
	 ('Brocoli','Ail',FALSE),
	 ('Brocoli','Échalote',FALSE),
	 ('Brocoli','Salade',FALSE),
	 ('Brocoli','Tomate',FALSE),
	 ('Chou-fleur','Salade',FALSE),
	 ('Chou-fleur','Tomate',FALSE),
	 ('Chou-fleur','Fenouil',FALSE),
	 ('Chou-rave','Fenouil',FALSE),
	 ('Navet','Radis noir',FALSE),
	 ('Radis noir','Chou pommé',FALSE),
	 ('Radis noir','Brocoli',FALSE),
	 ('Radis noir','Roquette',FALSE),
	 ('Radis noir','Concombre',FALSE),
	 ('Roquette','Pomme de terre',FALSE),
	 ('Roquette','Chou pommé',FALSE),
	 ('Roquette','Navet',FALSE),
	 ('Carotte','Fenouil',FALSE),
	 ('Carotte','Betterave',FALSE),
	 ('Céleri','Salade',FALSE),
	 ('Céleri','Carotte',FALSE),
	 ('Céleri','Panais',FALSE),
	 ('Fenouil','Concombre',FALSE),
	 ('Fenouil','Haricots nains',FALSE),
	 ('Fenouil','Chou pommé',FALSE),
	 ('Concombre','Pomme de terre',FALSE),
	 ('Courgette','Melon',FALSE),
	 ('Courgette','Concombre',FALSE),
	 ('Citrouille','Pomme de terre',FALSE),
	 ('Haricots nains','Haricots à rame',FALSE),
	 ('Épinard','Betterave',FALSE),
	 ('Épinard','Blette',FALSE),
	 ('Asperge','Oignon',FALSE);
